Do not restore save if the cache does not exist
actions/stale pull request #1057
Opened 2023-07-21 05:47 UTC by dsame

**Description:**
Utilize https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#list-github-actions-caches-for-a-repository 
to check if the cache exist and skip the restore if it does not

**Related issue:**
[link to the original issue.](https://github.com/github/c2c-actions-akvelon/issues/32)
[link to the related issue.](https://github.com/actions/runner-images-internal/issues/5239)

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2023-07-25 09:19 UTC, nikolai-laevskii requested changes
Aside from minor naming

2023-07-25 09:43 UTC, dusan-trickovic approved these changes
LGTM

2023-07-25 09:57 UTC, nikolai-laevskii approved these changes

2023-07-25 10:03 UTC, dsame commented on src/classes/state/state-cache-storage.ts
> +const checkCacheExist = async (cacheKey: string): Promise<boolean> => {
fixed

2023-07-25 10:04 UTC, dsame commented on src/classes/state/state-cache-storage.ts
> +      const cacheExist = await checkCacheExist(CACHE_KEY);
fixed

2023-07-25 10:15 UTC, nikolai-laevskii approved these changes

2023-07-25 13:16 UTC, marko-zivic-93 approved these changes

2023-07-25 14:55 UTC, MaksimZhukov approved these changes

2023-07-26 08:23 UTC, IvanZosimov commented on src/classes/state/state-cache-storage.ts
> +    core.debug(`$Error checking if cache exist: ${error.message}`);
```suggestion
    core.debug(`Error checking if cache exist: ${error.message}`);
```
Excessive dollar sign?

2023-07-26 13:01 UTC, dmitry-shibanov approved these changes

2023-07-27 08:21 UTC, merged