chore(logs): add more logs and better dry-run
actions/stale pull request #463
Opened 2021-05-24 21:17 UTC by C0ZEN

FYI, you can read the commits to have a better description.

## Changes
- [x] Add more logs
- [x] Change the dry-run to cover more code
- [x] Remove bad default values for some options

Closes #462
Closes #461

2021-06-02 22:00 UTC, luketomlinson requested changes
Maybe I'm reading it incorrectly, but I think some conditions might be swapped?  I'd appreciate any explanation if I'm missing something 😅

2021-06-03 20:10 UTC, C0ZEN commented on src/classes/issues-processor.ts
> +        if (this.options.debugOnly) {
OMG, thank you for the in-depth review because I didn't see this neglect at all.
Continue to be vigilant, trust is overrated! 🤟🏻

2021-06-03 20:22 UTC, C0ZEN commented on dist/index.js
> +                    if (this.options.debugOnly) {
5437c6f78f38bf567c9ab9730de1501ac0e01a10

2021-06-03 20:22 UTC, C0ZEN commented on src/classes/issues-processor.ts
> +        if (this.options.debugOnly) {
5437c6f78f38bf567c9ab9730de1501ac0e01a10

2021-06-03 20:22 UTC, C0ZEN commented on src/classes/issues-processor.ts
> +      if (this.options.debugOnly) {
5437c6f78f38bf567c9ab9730de1501ac0e01a10

2021-06-03 20:23 UTC, C0ZEN commented
@luketomlinson nice catch, thanks!

2021-06-07 13:49 UTC, luketomlinson approved these changes

2021-06-07 13:49 UTC, merged