docs(readme): add branch hint
actions/stale pull request #532
Opened 2021-07-15 10:26 UTC by flaxel

## Changes

- [x] add description for branch hit

## Context

missing description

closes #529

2021-07-15 13:50 UTC, luketomlinson requested changes

2021-07-15 13:50 UTC, luketomlinson commented on README.md
> +The configuration must be on the default branch und the default values will:
```suggestion
The configuration must be on the default branch and the default values will:
```

2021-07-15 14:23 UTC, flaxel commented on README.md
> +The configuration must be on the default branch und the default values will:
Oh shit... Thanks! 😄

2021-08-19 17:20 UTC, C0ZEN commented
up

2021-09-08 17:40 UTC, luketomlinson approved these changes

2021-09-08 17:40 UTC, merged